// Code generated by "stringer -type CmdType -output z_cmdtype_string.go ."; DO NOT EDIT.

package tdaq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdUnknown-0]
	_ = x[CmdJoin-1]
	_ = x[CmdConfig-2]
	_ = x[CmdInit-3]
	_ = x[CmdReset-4]
	_ = x[CmdStart-5]
	_ = x[CmdStop-6]
	_ = x[CmdTerm-7]
	_ = x[CmdStatus-8]
	_ = x[CmdLog-9]
}

const _CmdType_name = "CmdUnknownCmdJoinCmdConfigCmdInitCmdResetCmdStartCmdStopCmdTermCmdStatusCmdLog"

var _CmdType_index = [...]uint8{0, 10, 17, 26, 33, 41, 49, 56, 63, 72, 78}

func (i CmdType) String() string {
	if i >= CmdType(len(_CmdType_index)-1) {
		return "CmdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CmdType_name[_CmdType_index[i]:_CmdType_index[i+1]]
}
