// Code generated by "stringer -type CmdType -output z_cmdtype_string.go ."; DO NOT EDIT.

package tdaq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdUnknown-0]
	_ = x[CmdJoin-1]
	_ = x[CmdHBeat-2]
	_ = x[CmdConfig-3]
	_ = x[CmdInit-4]
	_ = x[CmdReset-5]
	_ = x[CmdStart-6]
	_ = x[CmdStop-7]
	_ = x[CmdQuit-8]
	_ = x[CmdStatus-9]
	_ = x[CmdLog-10]
}

const _CmdType_name = "CmdUnknownCmdJoinCmdHBeatCmdConfigCmdInitCmdResetCmdStartCmdStopCmdQuitCmdStatusCmdLog"

var _CmdType_index = [...]uint8{0, 10, 17, 25, 34, 41, 49, 57, 64, 71, 80, 86}

func (i CmdType) String() string {
	if i >= CmdType(len(_CmdType_index)-1) {
		return "CmdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CmdType_name[_CmdType_index[i]:_CmdType_index[i+1]]
}
