// Code generated by "stringer -type FrameType ."; DO NOT EDIT.

package iodaq

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FrameInvalid-0]
	_ = x[FrameStatus-1]
	_ = x[FrameData-2]
	_ = x[FrameCmd-3]
	_ = x[FrameOK-4]
	_ = x[FrameErr-5]
}

const _FrameType_name = "FrameInvalidFrameStatusFrameDataFrameCmdFrameOKFrameErr"

var _FrameType_index = [...]uint8{0, 12, 23, 32, 40, 47, 55}

func (i FrameType) String() string {
	if i >= FrameType(len(_FrameType_index)-1) {
		return "FrameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FrameType_name[_FrameType_index[i]:_FrameType_index[i+1]]
}
