// Code generated by "stringer -type StateKind -output z_statekind_string.go"; DO NOT EDIT.

package fsm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error-0]
	_ = x[UnConf-1]
	_ = x[UnInit-2]
	_ = x[Conf-3]
	_ = x[Stopped-4]
	_ = x[Running-5]
}

const _StateKind_name = "ErrorUnConfUnInitConfStoppedRunning"

var _StateKind_index = [...]uint8{0, 5, 11, 17, 21, 28, 35}

func (i StateKind) String() string {
	if i >= StateKind(len(_StateKind_index)-1) {
		return "StateKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateKind_name[_StateKind_index[i]:_StateKind_index[i+1]]
}
