// Code generated by "stringer -type StateKind -output z_statekind_string.go"; DO NOT EDIT.

package fsm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnConf-0]
	_ = x[Conf-1]
	_ = x[Init-2]
	_ = x[Stopped-3]
	_ = x[Running-4]
	_ = x[Exiting-5]
	_ = x[Error-6]
}

const _StateKind_name = "UnConfConfInitStoppedRunningExitingError"

var _StateKind_index = [...]uint8{0, 6, 10, 14, 21, 28, 35, 40}

func (i StateKind) String() string {
	if i >= StateKind(len(_StateKind_index)-1) {
		return "StateKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateKind_name[_StateKind_index[i]:_StateKind_index[i+1]]
}
