// Code generated by "stringer -type Type ."; DO NOT EDIT.

package coms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Init-0]
	_ = x[Config-1]
	_ = x[Reset-2]
	_ = x[Start-3]
	_ = x[Stop-4]
	_ = x[Terminate-5]
	_ = x[Status-6]
	_ = x[Log-7]
	_ = x[Ok-8]
	_ = x[Err-9]
}

const _Type_name = "InitConfigResetStartStopTerminateStatusLogOkErr"

var _Type_index = [...]uint8{0, 4, 10, 15, 20, 24, 33, 39, 42, 44, 47}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
